### PR TITLE
Context menu name for components

### PR DESCRIPTION
**Pull request by bakcxoj**
It would be nice to have the ability to set a custom name for components in the context menu.

### CODE REVIEW

**Comment by Ni55aN** [comment]
Good suggestion. I have implemented a more flexible method

**Comment by Ni55aN** [comment]
```js
class MyComponent {
    constructor() {
        super("My comp");
        this.contextMenuItem = "Add My comp";
    }
}
///
editor.use(ContextMenuPlugin, {
rename(component) { return component.contextMenuItem || contextMenuItem.name }
});
```

**Comment by bakcxoj** [comment]
Hey cool! Is this live on npm?

**Comment by bakcxoj** [comment]
@Ni55aN This update doesn't seem to be on npm

**Comment by bakcxoj** [comment]
Nevermind, my npm wasn't updating it for some reason. I had to manually set the version.

**Pull request closed without merging**
