### PR TITLE
No more Lodash

### LINKED ISSUE #8: Reduce dependencies
You could use `npm i lodash.debounce` instead of the full lodash.

### PR DESCRIPTION
**Pull request by mrauhu**
Greetings, Vitaliy.

In this pull request I removed the Lodash library from dependencies.

Bundle size reduced, now it's 72 KB (parsed) or 25 KB (minified and gzipped).

Also fixes #8.

Best wishes,
Sergey.

### CODE REVIEW

**Comment by Ni55aN** [comment]
What are the benefits? As I know many bunders have the tree shaking so they will not inlude unnecessary code from lodash

**Comment by mrauhu** [comment]
@Ni55aN tree shaking is not working. I'm tested it with Vue CLI.

> What are the benefits?

Less size, no dependencies.

**Comment by Ni55aN** [comment]
>Less size

`import debounce from 'lodash/debounce ';` seems to be enough for tree shaking

> no dependencies

what if some other function from lodash will be needed?

**Comment by mrauhu** [comment]
> `import debounce from 'lodash/debounce` '; seems to be enough for tree shaking

I'm tried this way.

Not works, because `retejs/context-menu-plugin` has outdated Rollup dependencies so I can't install a Rollup plugin for support of the `import`.

So, instead updating the `rete-cli`, which also has outdated Rollup dependencies with deprecated config format, I'm just removed `lodash`.

> what if some other function from lodash will be needed?

Lodash in year 2019?

Maybe use native ECMAScript functions instead.

**Comment by Ni55aN** [comment]
> I'm tried this way. Not works, 

Really? I just tried this:

---

`npm run build`
`browserify build/context-menu-plugin.min.js -o build/test.js`

test.js -> 772 kb (includes lodash, vue.js, etc)

---

replace `import { debounce } from 'lodash';` with `import debounce from 'lodash/debounce';`
`npm run build`
`browserify build/context-menu-plugin.min.js -o build/test.js`

test.js -> 246 kb (includes the `debounde` function from lodash, vue.js, etc)

**Comment by Ni55aN** [comment]
> Lodash in year 2019?
> Maybe use native ECMAScript functions instead.

uniqBy, groupBy and so on

**Comment by mrauhu** [comment]
@Ni55aN 

> Really? I just tried this:
> npm run build

Example:

```
git checkout v0.5.0
# Use `import debounce from 'lodash/debounce';` in `src/menu/debounceHide.js`
npm build
```

Output:
```
> rete-context-menu-plugin@0.5.0 build \rete\context-menu-plugin
> rete --build rete.config.js

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
'lodash/isFunction' is imported by src\index.js, but could not be resolved – treating it as an external dependency
'lodash/debounce' is imported by src\menu\debounceHide.js, but could not be resolved – treating it as an external dependency
'lodash/isFunction' is imported by src\index.js, but could not be resolved – treating it as an external dependency
'lodash/debounce' is imported by src\menu\debounceHide.js, but could not be resolved – treating it as an external dependency
'lodash/isFunction' is imported by src\index.js, but could not be resolved – treating it as an external dependency
'lodash/debounce' is imported by src\menu\debounceHide.js, but could not be resolved – treating it as an external dependency

Process finished with exit code 0

```

**Comment by mrauhu** [comment]
```
browserify build/context-menu-plugin.min.js -o build/test.js
```

Don't see `browserify` in dev dependencies.

**Comment by Ni55aN** [comment]
> Don't see browserify in dev dependencies.

it is not necessary, it was an example

**Comment by Ni55aN** [comment]
Another example:
```js
// src/index.js in the test project
import ContextMenuPlugin from '../../context-menu-plugin';

console.log(ContextMenuPlugin);
```

```js
// webpack.config.js

module.exports = { // polyfill required
    entry: ['babel-polyfill', './src/index.js'],
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env']
            }
          }
        }
      ]
    },
    resolve: {
      extensions: ['*', '.js', '.jsx']
    },
    output: {
      path: __dirname + '/dist',
      publicPath: '/',
      filename: 'bundle.js'
    },
    devServer: {
      contentBase: './dist'
    }
  };
```

### Context menu plugin:

```js
import { debounce } from 'lodash';
```
bundle.js -> 249 kb

---

```js
import debounce from 'lodash/debounce';
``` 
bundle.js -> 181 kb

---

```js
function debounce(next, ms) {
    let timeout;
    return (...args) => {
      clearTimeout(timeout);
      timeout = setTimeout(() => {
        next(...args);
      }, ms);
    };
  }
``` 

bundle.js -> 180 kb

**Pull request closed without merging**
